# Generated by Django 5.2.7 on 2025-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_users_user_id_users_groups_users_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='full_name',
            field=models.CharField(default='Неизвестный пользователь', max_length=200),
            preserve_default=False,
        ),
    ]
