# Generated by Django 5.2.7 on 2025-10-21 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_number', models.IntegerField()),
                ('answer_text', models.TextField()),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_question', models.TextField()),
                ('difficulty', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('discrimination', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('guessing', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users')),
                ('correct_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.answers')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.topic')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.questions'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_of_questions', models.IntegerField(blank=True, null=True)),
                ('test_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.topic')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestSessions',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_ability_estimate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('standard_error', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('next_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.questions')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.status')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.test')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.users')),
            ],
            options={
                'db_table': 'test_sessions',
            },
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('user_answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_in_test', models.IntegerField()),
                ('ability_after_answer', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('standard_error_after', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('probability_of_correct', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.questions')),
                ('selected_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.answers')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.testsessions')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.test')),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.questions')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.test')),
            ],
            options={
                'db_table': 'test_questions',
                'unique_together': {('test', 'question')},
            },
        ),
    ]
